artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  local_data_file: artifacts/data_ingestion/itens.xlsx


data_validation:
  root_dir: artifacts/data_validation
  data_file_path: artifacts/data_ingestion/itens.xlsx
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  transformed_data_path: artifacts/data_transformation/df_encoded_ar.xlsx

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.xlsx
  test_data_path: artifacts/data_transformation/test.xlsx
  model_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.xlsx
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json